version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  kafka:
    image: apache/kafka-native
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:

      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT

      # KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091

      # Use DOCKER for inter-broker comms
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Single-node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  processing_elastic:
    image: processing_elastic:1.0
    container_name: processing_elastic
    depends_on:
      - kafka
      - elasticsearch

  processing_mongo:
    image: processing_mongo:1.0
    container_name: processing_mongo
    depends_on:
      - kafka
      - mongodb

  service_kafka:
    image: service_kafka:1.0
    container_name: service_kafka
    depends_on:
      - kafka

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"