FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY kafka_connection.py .
COPY files/ files/file_path.py

CMD ["python3", "main.py"]